In [5]:
import pandas as pd
import boto3

from matplotlib import pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [1]:
%env AWS_ACCESS_KEY_ID=ASIAV65BRBK4G3RANL5E
%env AWS_SECRET_ACCESS_KEY=8b8N6Wx9OtxlBEOTlBNb88CX1gKy9Qm/PuKbvI4F
%env AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEOX//////////wEaCXVzLWVhc3QtMSJIMEYCIQCgba7BsTMrmEA8qTfNT1u+n63VdCxMMuCZ2ZIYg2f8NAIhALUgZdSHH2b8bo5x2V3xoRE3w+7WWH17W7IUzouX5ICXKu8CCE4QAxoMNDA5OTcxMjY0MTg0Igze6raOUigYd0J62QMqzALcmSGrHXBDPEZNmbe4s4am86cklk+7Jvsz3NzCZzTvppafSuuSDrYSc8kOsvmKgvpQY2kwsZQvgXKtXxSW8OOqDZP85T3VDCFYFDbxUxhOPmbFUeNs55+KzWk1twrGrmn94V6Q9niPJjVRcD41icaEjr2SeWVwEg3LraG8mKbIn4TxuxFD9AdBcmsOqjyN+oSm/oMqemTgIceeEgJXu/jRWRnSeVlKA4IpL4IIlIgOqR+0aZbTMeX9ClWgPqMYUC8lmdkayE+4pcSGT3SA4Jqdw+81YjeZXdjLMWjYva35JGtKsUiuvTB6e90locO2JkkL5qjqHRuOITk0SUJhRtTTXM1R239BgN0iAs5dXfxKdTqnKu1jqcmrR+hlU4SNtd0Ly0CAxmWANoXVwa9obf9RjU6UYMp2Er+a0h4rt+6RJlJTUcvotBY0/Tvd1TDh9uekBjqmAYrC0YRM/C4e5sEni7OBALzW1HTitlxymcbh/AyEBsaZJcXKl8XolsDJ636aFtSDSpWP/sc8UktVkLMCII/eFhqyXnbBN98S1i+OCN0VGjB/ore72Sj016m+BvjFOZl8NCMCM/oJCc1n/iYa7z+aQaZB02WXtL3DeJdOYTG8iNmEBNB1AQUVD2utEH42CR3A7RVTJX74s/X/RPtUpJSH8sOirxjiAM8=

env: AWS_ACCESS_KEY_ID=ASIAV65BRBK4G3RANL5E
env: AWS_SECRET_ACCESS_KEY=8b8N6Wx9OtxlBEOTlBNb88CX1gKy9Qm/PuKbvI4F
env: AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEOX//////////wEaCXVzLWVhc3QtMSJIMEYCIQCgba7BsTMrmEA8qTfNT1u+n63VdCxMMuCZ2ZIYg2f8NAIhALUgZdSHH2b8bo5x2V3xoRE3w+7WWH17W7IUzouX5ICXKu8CCE4QAxoMNDA5OTcxMjY0MTg0Igze6raOUigYd0J62QMqzALcmSGrHXBDPEZNmbe4s4am86cklk+7Jvsz3NzCZzTvppafSuuSDrYSc8kOsvmKgvpQY2kwsZQvgXKtXxSW8OOqDZP85T3VDCFYFDbxUxhOPmbFUeNs55+KzWk1twrGrmn94V6Q9niPJjVRcD41icaEjr2SeWVwEg3LraG8mKbIn4TxuxFD9AdBcmsOqjyN+oSm/oMqemTgIceeEgJXu/jRWRnSeVlKA4IpL4IIlIgOqR+0aZbTMeX9ClWgPqMYUC8lmdkayE+4pcSGT3SA4Jqdw+81YjeZXdjLMWjYva35JGtKsUiuvTB6e90locO2JkkL5qjqHRuOITk0SUJhRtTTXM1R239BgN0iAs5dXfxKdTqnKu1jqcmrR+hlU4SNtd0Ly0CAxmWANoXVwa9obf9RjU6UYMp2Er+a0h4rt+6RJlJTUcvotBY0/Tvd1TDh9uekBjqmAYrC0YRM/C4e5sEni7OBALzW1HTitlxymcbh/AyEBsaZJcXKl8XolsDJ636aFtSDSpWP/sc8UktVkLMCII/eFhqyXnbBN98S1i+OCN0VGjB/ore72Sj016m+BvjFOZl8NCMCM/oJCc1n/iYa7z+aQaZB02WXtL3DeJdOYTG8iNmEBNB1AQUVD2utEH42CR3A7RVTJX74s/X/RPtUpJSH8sOirxjiAM8=

In [2]:
!aws s3 ls cur-billing-pocs/CUR/CUR/CUR/year=2023/month=4/

2023-05-03 11:39:17      66627 CUR-00001.snappy.parquet
2023-05-03 11:39:17   27757658 CUR-00002.snappy.parquet

In [3]:
s3 = boto3.client('s3')
s3.download_file('cur-billing-pocs', 'CUR/CUR/CUR/year=2023/month=4/CUR-00002.snappy.parquet', 'cur_00001.parquet')
s3.download_file('cur-billing-pocs', 'CUR/CUR/CUR/year=2023/month=4/CUR-00002.snappy.parquet', 'cur_00002.parquet')

NameError: name 'boto3' is not defined

In [18]:
cur_2 = pd.read_parquet('cur_00001.parquet', engine='pyarrow')
cols = list(cur_2.columns)
print(f'Shape: {cur_2.shape}')
cur_2.head()

Shape: (970210, 218)

,identity_line_item_id,identity_time_interval,bill_invoice_id,bill_invoicing_entity,bill_billing_entity,bill_bill_type,bill_payer_account_id,bill_billing_period_start_date,bill_billing_period_end_date,line_item_usage_account_id,...,savings_plan_savings_plan_effective_cost,savings_plan_amortized_upfront_commitment_for_billing_period,savings_plan_recurring_commitment_for_billing_period,resource_tags_aws_cloudformation_logical_id,resource_tags_aws_cloudformation_stack_id,resource_tags_aws_cloudformation_stack_name,resource_tags_aws_created_by,resource_tags_user_a_w_s_solutions,resource_tags_user_name,resource_tags_user_lambda_created_by
0,hkfdaickefiyhcisqmcrveadihyywe3gpjeuqblgh6euhs...,2023-04-01T00:00:00Z/2023-05-01T00:00:00Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,403082213880,...,0.0,0.0,0.0,,,,,,,
1,n2hi7l2oehxyii3t5oieizemmrevrdumsjh4lgq77b4osx...,2023-04-01T00:00:00Z/2023-05-01T00:00:00Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,415141232874,...,0.0,0.0,0.0,,,,,,,
2,uvx5q2n7njsk5gbobcnkcrt4rkeehvjbujl6eiay4zsjl5...,2023-04-01T00:00:00Z/2023-05-01T00:00:00Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,846874130087,...,0.0,0.0,0.0,,,,,,,
3,kyy35fghntwhu66pyhexiq543hvjjkezzrkjcmiam3jm6j...,2023-04-01T00:00:00Z/2023-05-01T00:00:00Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,400306697317,...,0.0,0.0,0.0,,,,,,,
4,evytcnwhf3dn3ngq2awt3hmk5av2spvxbfhfxeir7luilk...,2023-04-01T00:00:00Z/2023-04-18T13:19:01Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,550493734412,...,0.0,0.0,0.0,,,,,,,

In [3]:
cur_1 = pd.read_parquet('cur_00001.parquet', engine='pyarrow')
cols = list(cur_1.columns)
print(f'Shape: {cur_1.shape}')
cur_1.head()

Shape: (970210, 218)

,identity_line_item_id,identity_time_interval,bill_invoice_id,bill_invoicing_entity,bill_billing_entity,bill_bill_type,bill_payer_account_id,bill_billing_period_start_date,bill_billing_period_end_date,line_item_usage_account_id,...,savings_plan_savings_plan_effective_cost,savings_plan_amortized_upfront_commitment_for_billing_period,savings_plan_recurring_commitment_for_billing_period,resource_tags_aws_cloudformation_logical_id,resource_tags_aws_cloudformation_stack_id,resource_tags_aws_cloudformation_stack_name,resource_tags_aws_created_by,resource_tags_user_a_w_s_solutions,resource_tags_user_name,resource_tags_user_lambda_created_by
0,hkfdaickefiyhcisqmcrveadihyywe3gpjeuqblgh6euhs...,2023-04-01T00:00:00Z/2023-05-01T00:00:00Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,403082213880,...,0.0,0.0,0.0,,,,,,,
1,n2hi7l2oehxyii3t5oieizemmrevrdumsjh4lgq77b4osx...,2023-04-01T00:00:00Z/2023-05-01T00:00:00Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,415141232874,...,0.0,0.0,0.0,,,,,,,
2,uvx5q2n7njsk5gbobcnkcrt4rkeehvjbujl6eiay4zsjl5...,2023-04-01T00:00:00Z/2023-05-01T00:00:00Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,846874130087,...,0.0,0.0,0.0,,,,,,,
3,kyy35fghntwhu66pyhexiq543hvjjkezzrkjcmiam3jm6j...,2023-04-01T00:00:00Z/2023-05-01T00:00:00Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,400306697317,...,0.0,0.0,0.0,,,,,,,
4,evytcnwhf3dn3ngq2awt3hmk5av2spvxbfhfxeir7luilk...,2023-04-01T00:00:00Z/2023-04-18T13:19:01Z,1332346585,Amazon AWS Serviços Brasil Ltda.,AWS,Anniversary,409971264184,2023-04-01,2023-05-01,550493734412,...,0.0,0.0,0.0,,,,,,,